version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current

    steps:
      - checkout

      # Récupérer les dépendances de l'application
      - run:
          name: Install dependencies
          command: npm install

      # Construire l'image Docker
      - run:
          name: Build Docker image
          command: docker build -t my-node-app .

      # Pousser l'image Docker sur le registre
      - run:
          name: Push Docker image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker tag my-node-app $DOCKER_USER/my-node-app:latest
            docker push $DOCKER_USER/my-node-app:latest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build