version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current

    steps:
      - checkout

      # Récupérer les dépendances de l'application
      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Build Docker image
          command: docker build -t my-node-app .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build