version: 2.1

executors:
  node-docker-executor:
    docker:
      - image: circleci/node:16-browsers  # Image de base avec Node.js et outils
    working_directory: ~/repo

jobs:
  build:
    executor: node-docker-executor
    steps:
      - checkout  # Récupère le code source

      # Installe les dépendances
      - run:
          name: Install Dependencies
          command: npm install

      # Construis l'image Docker
      - setup_remote_docker:  # Permet d'utiliser Docker en conteneur
          version: 20.10.8
      - run:
          name: Build Docker Image
          command: |
            docker build -t mon-utilisateur/mon-app:$CIRCLE_SHA1 .
      
      workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
